// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateCA(arg1:main.CAInput):Promise<string>;

export function CreateCert(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function DeleteCA(arg1:string):Promise<string>;

export function DeleteCert(arg1:string):Promise<string>;

export function ExportToPFX(arg1:string,arg2:string):Promise<string>;

export function GenerateInstaller(arg1:string):Promise<string>;

export function InspectCert(arg1:string):Promise<main.CertDetails>;

export function InstallCA(arg1:string):Promise<string>;

export function IsAdmin():Promise<boolean>;

export function ListCAs():Promise<Array<string>>;

export function ListCerts():Promise<Array<string>>;

export function OpenOutputDir():Promise<string>;
