// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCA(arg1) {
  return window['go']['main']['App']['CreateCA'](arg1);
}

export function CreateCert(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateCert'](arg1, arg2, arg3, arg4);
}

export function DeleteCA(arg1) {
  return window['go']['main']['App']['DeleteCA'](arg1);
}

export function DeleteCert(arg1) {
  return window['go']['main']['App']['DeleteCert'](arg1);
}

export function ExportToPFX(arg1, arg2) {
  return window['go']['main']['App']['ExportToPFX'](arg1, arg2);
}

export function GenerateInstaller(arg1) {
  return window['go']['main']['App']['GenerateInstaller'](arg1);
}

export function InspectCert(arg1) {
  return window['go']['main']['App']['InspectCert'](arg1);
}

export function InstallCA(arg1) {
  return window['go']['main']['App']['InstallCA'](arg1);
}

export function IsAdmin() {
  return window['go']['main']['App']['IsAdmin']();
}

export function ListCAs() {
  return window['go']['main']['App']['ListCAs']();
}

export function ListCerts() {
  return window['go']['main']['App']['ListCerts']();
}
